#!/bin/bash

set -e
set -u

. "$plugin_dir/functions"

create_app_skel
install_tomcat7
install_server_config
install_app
install_java_agent
install_java_functions
write_config
write_java_opts
write_control
