#!/bin/bash
set -e
set -u

control_dir="$(dirname $0)"
. $control_dir/config
. $control_dir/java/functions

java_opts="$(java_opts $control_dir)"

export CATALINA_OPTS=$catalina_opts

exec bash -c "
$java \
  $java_opts \
  -Dcatalina.home=$cataline_home \
  -Dcatalina.base=$catalina_base \
  -Djava.io.tmpdir=$app_tmp \
  $catalina_opts \
  -cp $catalina_home/bin/bootstrap.jar:$catalina_home/bin/tomcat-juli.jar \
  org.apache.catalina.startup.Bootstrap \
  start
"
